src/components/Projects/index.js
Added the project count to the Lagoon Dashboard - Adresses https://github.com/uselagoon/lagoon/issues/1909
=> Added project count to UI

src/pages/settings/index.js
=> lowercase keys in SSH keys

src/components/ProjectDetailsSidebar/index.js
Fix the pull requests enabled to show in the projects side bar
=> fix: show pull requests enabled in the ui

src/components/Projects/index.js
Relates to issue [3255](https://github.com/uselagoon/lagoon/issues/3255) - updated input field to disallow invalid characters.
Explain the **details** for making this change. What existing problem does the pull request solve?
closes #49
=> Disallow invalid characters

src/components/BulkDeployments/index.js, src/components/Button/index.js, src/components/DeploymentsByFilter/index.js
Adresses https://github.com/uselagoon/lagoon-ui/issues/52
Capitalised wording and increased margin.
=> Small UI updates to the Cancel button

src/components/Insights/index.js
Adresses https://github.com/uselagoon/lagoon-ui/issues/71 
Insight count and pluralization updates when filtering results.
=> Updating insights count to update with filtered results

src/components/Deployment/index.js, src/components/LogViewer/index.js
This PR changes the look/feel of the way parsed/raw logs are displayed to the following
=> Changes pretty-printing functionality in UI

src/components/Deployment/index.js, src/components/LogViewer/index.js
closes #82 by forcing the last section to always be open.
=> Adds open last section by default

src/components/SshKeys/AddSshKey.js
Closes https://github.com/uselagoon/lagoon-ui/issues/59
Closes https://github.com/uselagoon/lagoon-ui/issues/64
Adding trim prior to the validation on newline occurences.
=> Adding trim prior to validation

src/components/HeaderMenu/index.js
callback didn't "wait" for listners before removing dropdown from the ui
=> Fix Signout button in dropdown

src/components/BulkDeployments/index.js, src/components/Deployment/index.js, src/components/DeploymentsByFilter/index.js
now that queued status is implemented, there needs to be a way to cancel them, this adds that support
Screenshot of problem using this PR as the example, no cancel button visible
=> fix: support queued cancellations

src/components/Organizations/AddUserToGroup/index.js
Fixes cancel button on Groups modal.
=> Fixes cancel button on Groups modal

src/components/AddTask/components/InvokeRegisteredTask.js, src/lib/query/EnvironmentWithTasks.js
https://github.com/uselagoon/lagoon/pull/3478 introduced default values and optional fields
I am completely aware that this probably doesn't work 100% but it works enough to validate an idea. Hopefully someone can implement this better
=> feat: default task variables values

src/components/AddTask/components/DrushArchiveDump.js, src/components/AddTask/components/DrushCacheClear.js, src/components/AddTask/components/DrushCron.js, src/components/AddTask/components/DrushRsyncFiles.js, src/components/AddTask/components/DrushSqlDump.js, src/components/AddTask/components/DrushSqlSync.js, src/components/AddTask/components/DrushUserLogin.js, src/components/AddTask/components/InvokeRegisteredTask.js, src/components/AddTask/components/Styles.tsx, src/components/AddTask/index.js, src/components/DeployLatest/StyledDeployLatest.js, src/components/DeployLatest/index.js, src/pages/deployments.js, src/pages/tasks.js
Introduces funtionality that refetches the data & refreshes the Deployments/Tasks components on mutation success.
closes #100
=> Change: Add refetch functionality for deployments & tasks

src/components/AddVariable/StyledAddVariable.tsx, src/components/DeleteVariable/StyledDeleteVariable.tsx
Interim fix for variable buttons - table + buttons to be reworked in the near future.
=> Fix: Styling fix for Variable buttons

src/components/Environments/index.js, src/components/NewEnvironment/StyledNewEnvironment.tsx, src/components/NewEnvironment/index.js, src/pages/project.js
Moved the `Create Environment` button to the end of the list of environments on the Projects page.
=> Repositioned Create Environment button

src/components/ResultsLimited/index.js, src/pages/backups.js, src/pages/deployments.js, src/pages/tasks.js
the issue also affected tasks and backups list.
closes #172
=> update limited results without refreshing

src/components/CancelTask/index.tsx, src/components/Organizations/AddUserToGroup/index.js, src/components/Organizations/AddUserToOrganization/index.js, src/components/Organizations/GroupMembers/index.js, src/components/Organizations/Manage/index.js, src/components/Organizations/Notifications/AddNotifications.tsx, src/components/Organizations/Organization/index.js, src/lib/query/organizations/GroupByNameAndOrganization.js, src/lib/query/organizations/OrganizationByID.js, src/lib/query/organizations/OrganizationNotificationsByID.js, src/lib/query/organizations/ProjectAndOrganizationByID.js
- adds some missing button loading states;
- change quota `-1` display to unlimited;
- expose environment quota on overview page;
- fix firstname spaced differently to users with no first name on group members page;
- added ability to edit user role on group members page.;
- added ability edit organization owner/viewer role on manage page;
- fix cancel task error appearing multiple times;
=> fix multiple bugs

.storybook/mocks/api.ts, .storybook/mocks/mocks.ts
Adds `Organization Environments` to the Storybook `mocks` to fix the current test failures.
=> Fix: Adds Organization Environments to the Storybook mocks

src/components/AddTask/components/DrushCron.js
Removes duplicate task buttons for `drush cron`.
=> Fix: Remove duplicate task buttons

src/components/DeployTargets/DeployTargetsSkeleton.tsx, src/components/DeployTargets/StyledDeployTargets.tsx, src/components/DeployTargets/index.js
Various changes for consistency:
- Removes the top h3
- Left Aligns the table
- Minor breakpoint updates
closes https://github.com/uselagoon/lagoon-ui/issues/193
=> Various changes to the Deploy Targets page

src/components/Projects/ProjectsSkeleton.tsx, src/components/Projects/index.js, src/components/Projects/index.stories.tsx, src/pages/projects.js
This PR adds logic to permit searches done whilst the project page is loading to persist once the page is loaded.
closes #201
=> allow searching during page load

.github/workflows/ui-workflow.yaml, test/README.md
UI workflow based off of #184 
- formatting
- linting
- cypress tests (general / rbac/ organizations)
Relies on #221 and #222
=> UI workflow

src/components/Environment/index.js
Navigation didn't wait for the `SwitchActiveStandbyMutation`, also fixes the full page refresh
=> fix early nav causing NS_BINDING_ABORTED

cypress/e2e/general/settings.cy.ts, cypress/e2e/general/sidebarNav.cy.ts, cypress/e2e/organizations/groups.cy.ts, cypress/e2e/organizations/notifications.cy.ts, cypress/e2e/rbac/organizations/platformAndOrgOwnerJourney.cy.ts, cypress/support/actions/organizations/GroupsAction.ts, cypress/support/actions/organizations/NotificationsAction.ts, cypress/support/repositories/organizations/GroupsRepository.ts, cypress/support/repositories/organizations/NotificationsRepository.ts, cypress/support/repositories/settings/SettingsRepository.ts, package.json, src/components/SshKeys/index.js, yarn.lock
closes #231 
Fixes a couple flaky tests and updates cypress
=> fix a couple flaky tests

src/components/EnvironmentVariables/index.js
Corrects incorrect label in `EnvironmentVariables` component.
Closes https://github.com/uselagoon/lagoon-ui/issues/244
=> Fix: Corrects incorrect label

src/components/Organizations/Manage/index.js, src/components/Organizations/Organization/index.js
=> fix: swap owner and viewer colors red <-> blue

src/components/Organizations/GroupMembers/index.js
=> fix: Add project to group title text

cypress/support/repositories/organizations/NotificationsRepository.ts, src/components/Organizations/Notifications/Styles.tsx, src/components/Organizations/Notifications/index.js, src/components/Organizations/PaginatedTable/PaginatedTable.tsx, src/components/Organizations/PaginatedTable/Styles.tsx, src/components/Organizations/RemoveNotificationConfirm/index.js
=> Fix: Notification count, pagination, filtering, gql error displays

src/components/DeploymentsByFilter/index.js
=> fix: use dynamic length for deployments

src/components/Organizations/SharedStyles.tsx, src/components/Organizations/Users/index.js
=> change: show which user is being removed

src/components/Organizations/Notifications/index.js
closes #268 
adds an extra `updated` object to editState and properly decides which modal is open
=> fix: properly update org notifications

cypress/support/actions/organizations/OverviewAction.ts, src/components/Organizations/Organization/index.js
=> fix: autofill values on edit

cypress/support/actions/organizations/ProjectsActions.ts, cypress/support/repositories/organizations/ProjectsRepository.ts, src/components/Organizations/Projects/index.js, src/components/Organizations/SharedStyles.tsx
=> change: add "type project name to confirm" to org project deletion

src/components/link/ProjectChildPageLink.js
Fixes deploytarget link in project details.
closes https://github.com/uselagoon/lagoon-ui/issues/285
=> Fix: Fixes deploytarget link

src/components/ResultsLimited/index.js
=> fix: results to display breaking back navigation

src/components/Organizations/NewProject/index.js
=> fix: casing causing pullrequests being set to default true

public/mockServiceWorker.js, yarn.lock
Before:
```
65 vulnerabilities found - Packages audited: 2209
Severity: 3 Low | 34 Moderate | 28 High
Done in 2.53s.
```
After:
```
3 vulnerabilities found - Packages audited: 2263
Severity: 1 Moderate | 2 High
Done in 1.35s.
```
```
$ docker scout compare --to uselagoon/ui:core-v2.20.1 uselagoon/ui:pr-297
│               Analyzed Image               │              Comparison Image               
────────────────────┼────────────────────────────────────────────┼─────────────────────────────────────────────
Target            │  uselagoon/ui:pr-297                       │  uselagoon/ui:core-v2.20.1                  
digest          │  255dba21b58c                              │  6c2114deed91                               
tag             │  pr-297                                    │ …
```
=> build: yarn updates

src/components/Organizations/Groups/index.js, src/pages/organizations/groups.js
=> chore: remove check for 10<groups on add

src/components/SshKeys/StyledKeys.tsx, src/components/SshKeys/index.js, src/lib/query/Me.js, src/lib/variables.js, src/static/images/information.svg
Adds the last used timeframe to the SSH Keys table, and updates both created & last used to follow a similar format to Github.
Closes https://github.com/uselagoon/lagoon-ui/issues/298
=> Change: Adds last used to the ssh keys table

cypress/e2e/general/navigation.cy.ts, package.json, src/components/Breadcrumbs/Breadcrumb.tsx, src/components/Breadcrumbs/StyledBreadCrumb.tsx, yarn.lock
=> Change: Adds copy functionality to breadcrumbs

.storybook/mocks/mocks.ts, cypress/e2e/general/navigation.cy.ts, src/components/BulkDeployments/index.tsx, src/components/Deployment/DeploymentSkeleton.tsx, src/components/Deployment/StyledDeployment.js, src/components/Deployment/index.js, src/components/Deployments/index.tsx, src/components/DeploymentsByFilter/index.js, src/components/Task/StyledTask.tsx, src/components/Task/TaskSkeleton.tsx, src/components/Task/index.tsx, src/components/Tasks/TasksSkeleton.tsx, src/components/Tasks/index.tsx, src/lib/query/EnvironmentWithTask.js, src/lib/query/EnvironmentWithTasks.js, src/lib/util.js, src/styles/commonStyles.js, src/webpack.shared-config.js, tsconfig.json
duration visible on both pages, and a bit of reorganization
=> show task duration on /tasks and /tasks/taskSlug pages

cypress/support/commands.ts, src/components/Organizations/Groups/index.js, src/components/Organizations/PaginatedTable/PaginatedTable.tsx, src/components/Organizations/Projects/index.js, src/lib/query/organizations/OrganizationByName.groups.js, src/lib/query/organizations/OrganizationByName.js, src/lib/query/organizations/OrganizationByName.manage.js, src/lib/query/organizations/OrganizationByName.notification.js, src/lib/query/organizations/OrganizationByName.projects.js, src/lib/query/organizations/OrganizationByNameWithEnvVars.js, src/lib/query/organizations/OrganizationByNameWithEnvVarsValue.js, src/lib/query/organizations/UsersByOrganization.js, src/pages/organizations/groups.js, src/pages/organizations/manage.js, src/pages/organizations/notifications.js, src/pages/organizations/project.js, src/pages/organizations/projects.js
=> defer and use appropriate queries

package.json, public/mockServiceWorker.js, src/components/ActiveStandbyConfirm/index.tsx, src/components/AddTask/index.stories.tsx, yarn.lock
updates the version of Next.js to fix https://nextjs.org/blog/cve-2025-29927
=> chore: update yarn packages

cypress/e2e/organizations/manage.cy.ts, cypress/support/actions/organizations/ManageAction.ts, src/components/Organizations/AddUserToOrganization/index.js, src/components/Organizations/Manage/index.js
This PR shifts the underlying calls to manage org admins away from the deprecated graphql mutations.
=> Updates add, edit, and delete graphql calls away from deprecated
