uselagoon/lagoon-ui

src/components/Environment/index.js

Updated GitHub PR Link in Lagoon UI - Addresses - https://github.com/uselagoon/lagoon/issues/2040
Builds on existing PR https://github.com/uselagoon/lagoon/pull/2456

Correcting PR link in UI

---

src/components/ResultsLimited/index.js

All of the pages that use the `ResultsLimited` component check for `-1` to show all results, but the component was using `all` instead.
There was also an error being thrown for every selection caused by uninstantiated variables that has been fixed.
Closes #39

Fix showing all results when selecting "all"

---

src/components/AddTask/components/InvokeRegisteredTask.js

We've added a new advanced task definition argument type ENVIRONMENT_SOURCE_NAME_EXCLUDE_SELF that is currently unsupported in the UI - and defaults to simply displaying an input text box.
This fixes this issue.
closes #42

Adds case for ENVIRONMENT_SOURCE_NAME_EXCLUDE_SELF

---

package.json
yarn.lock

Somewhere in the dependency tree for git-url-parse, an update reintroduced https://caniuse.com/js-regexp-lookbehind
This PR just reverts the git-url-parse dependency tree to a know working version, but we should do the work to update the tree to latest.

fix git-url-parse dependencies at 11.1.2

---

src/components/LogViewer/index.js
src/pages/deployment.js

As pointed out in #65, there are times when viewing the entire log outside of the accordion is helpful.
This PR introduces a "parse logs" checkbox that when unchecked shows the logs back in the old style.
There's a persistent issue with state handing for sub-components for the page scroll logic. I've removed this - it's faulty and we need to new approach.
closes #65

Adds ability to display raw logs

---

src/lib/query/DeploymentsByFilter.js

This fixes the build duration being incorrect on the all builds page.

Passing in correct duration for build times on all builds page

---

server.js
src/components/DeploymentsByFilter/index.js
src/pages/alldeployments.js

This PR renames the `allBuilds` page to `deployments` in order to have consistent terms.
It also introduces a redirect to the newly named `alldeployments` page from `builds`

Adds redirection and changes builds to deployments

---

src/components/DeploymentsByFilter/index.js

In the `alldeployments` overview page, if there are no deployments currently available to the user, there are 2 divs displayed that show `No deployments`.
This removes one of them to make the page neater.

Fix: remove duplicate no deployments div

---

src/components/LogViewer/index.js

Just a minor word change for the first logs accordion to `Build Setup` instead of `Logs begin`. `Logs begin` doesn't really look that appealing, and `Build Setup` fits more with what is happening from that point on.
Before:
After:

chore: use build setup instead of logs begin

---

src/components/AddTask/logic.js
src/lib/query/EnvironmentWithTasks.js

Remake of https://github.com/uselagoon/lagoon/pull/3184 to be inline with current codebase. (Requires https://github.com/uselagoon/lagoon/pull/3382 to work - tasks page will error otherwise.)
UI changes split out into this PR.
- `showUi` logic updated in the `AddTask` component
- `getEnvironment` query updated with `adminTask` & `showUi`
Note that this PR requires lagoon-core v2.12.0 to be running, otherwise tasks page will  not load

Feature: UI changes for admin advanced tasks

---

src/components/SshKeys/AddSshKey.js

This PR removes the errant `=` character added to the SSH key regex. This symbol is unnecessary, as the `\S` symbol already matches on any `=` characters present.

Fix SSH Key Matching Regex

---

src/components/AddTask/logic.js
src/components/Tasks/index.js
src/lib/query/EnvironmentWithTask.js
src/lib/query/EnvironmentWithTasks.js

Revert showUi changes to support https://github.com/uselagoon/lagoon/pull/3393
Also add a label to tasks to identify they are admin run tasks:

feature: add admin label to admin tasks

---

src/lib/useTheme.tsx

emitting the storage event manually gets caught by the chat handler, which handles style switching for the chat widget (or anything in the future)

emit storage event manually

---

src/components/ActiveStandbyConfirm/StyledActiveStandbyConfirm.tsx
src/components/ActiveStandbyConfirm/index.tsx
src/components/ProjectDetailsSidebar/StyledProjectSidebar.tsx
src/layouts/GlobalStyles/index.tsx
src/styles/theme.ts

Fix for #129 & #130 - Adds the required styling to modals for dark mode + minor styling change on active standby modal content.
closes #129 #130

Fix: Included dark mode on modal and copy components

---

src/components/LogViewer/StyledLogViewer.tsx

Updated `StyledLogAccordion` to display the correct colour for failed deployments.
Closes #118

Fixed styling for failed deployments in the Log Accordion

---

.storybook/mocks/mocks.ts
src/components/Problems/index.js
src/stories/problems.stories.tsx

Currently in the problems list we're seeing repeated problems from services that share the same base images etc.
This PR cleans up this display by reducing repeated problems to a single problem with services concatenated with commas

Adds functionality to reduce repeated problems in the problems ui

---

src/components/Button/StyledButton.tsx
src/components/Button/index.tsx
src/components/Organizations/AddGroupToProject/index.js
src/components/Organizations/AddNotificationToProject/index.js
src/components/Organizations/AddUserToGroup/index.js
src/components/Organizations/AddUserToGroupSelect/index.tsx
src/components/Organizations/AddUserToOrganization/index.js
src/components/Organizations/GroupMembers/index.js
src/components/Organizations/Groups/index.js
src/components/Organizations/Manage/index.js
src/components/Organizations/NewGroup/index.js
src/components/Organizations/NewProject/index.js
src/components/Organizations/Notifications/index.js
src/components/Organizations/PaginatedTable/PaginatedTable.tsx
src/components/Organizations/PaginatedTable/Styles.tsx
src/components/Organizations/ProjectGroupMembers/index.js
src/components/Organizations/ProjectNotifications/index.js
src/components/Organizations/Projects/Styles.tsx
src/components/Organizations/Projects/index.js
src/components/Organizations/RemoveNotificationConfirm/index.js
src/components/Organizations/RemoveProjectGroupConfirm/index.js
src/components/Organizations/RemoveUserConfirm/index.js
src/components/Organizations/SharedStyles.tsx
src/components/Organizations/User/index.tsx
src/components/Organizations/Users/index.js
src/components/link/Project.js
src/pages/organizations/project.js

This PR does the following:
- fixes numeric sort in a couple places using `<PaginatedTable/>`
- adds "sort-by-role" functionality on the users page
- changes deletion modal texts to be accurate
- modals understand where the user is being updated or added
- users table has a "show/hide default users" filter
- each table now shows their row at their headers
- Adds project links to organization projects
- adds loading/disabled indicator to action buttons to avoid repeated mutations
- fixes group -> user link 
- and some smaller issues

some changes and improvements alongside bugfixes

---

src/components/AddVariable/StyledAddVariable.tsx
src/components/DeleteVariable/StyledDeleteVariable.tsx
src/components/DeleteVariable/index.js
src/components/EnvironmentVariables/StyledEnvironmentVariables.tsx
src/components/EnvironmentVariables/index.js
src/components/ProjectVariables/StyledProjectVariables.tsx
src/components/ProjectVariables/index.js

Update and Delete buttons on the Variables tabs were inheriting shared styles from Organizations, warping the buttons. Updated styling for variable buttons to prevent style bleed from shared css.

Fix: Styles conflicts on shared components

---

src/lib/query/organizations/GroupByNameAndOrganization.js
src/lib/query/organizations/OrganizationByID.js
src/lib/query/organizations/OrganizationNotificationsByID.js
src/lib/query/organizations/ProjectAndOrganizationByID.js
src/lib/query/organizations/UsersByOrganization.js

Updates the argument naming from `organization` to `id` for `organizationByID` queries.
**Note**: To be merged after the resolver update in PR https://github.com/uselagoon/lagoon/pull/3562

Change: Updated argument naming organizationByID

---

src/components/Organizations/NewGroup/index.js

Updates the `addGroup` mutation to `addGroupToOrganization` to reflect changes in the API.
**Note**: To be merged after the resolver update in PR https://github.com/uselagoon/lagoon/pull/3563

Change: Updated addGroupToOrganization mutation to reflect api changes

---

src/components/NewEnvironment/NewEnvironmentButton/index.js
src/components/NewEnvironment/index.js

Adds a error notification if the `deployEnvironmentBranch` mutation returns `Skipped: configured regex for all deploytargets does not match branchname`.

Include error handling for New Environment functionality

---

.storybook/mocks/api.ts
.storybook/mocks/mocks.ts
src/components/BulkDeployments/BulkDeploymentsSkeleton.tsx
src/components/BulkDeployments/StyledBulkDeployments.tsx
src/components/BulkDeployments/index.tsx
src/components/Deployment/index.js
src/components/Deployments/DeploymentsSkeleton.tsx
src/components/Deployments/StyledDeployments.tsx
src/components/Deployments/index.tsx
src/components/DeploymentsByFilter/StyledDeploymentsByFilter.js
src/components/DeploymentsByFilter/index.js
src/components/HoverTag/index.tsx
src/components/HoverTag/styles.tsx
src/lib/query/BulkDeploymentById.js
src/lib/query/DeploymentsByFilter.js
src/lib/query/EnvironmentWithDeployment.js
src/lib/query/EnvironmentWithDeployments.js

The HoverTag component is configurable : tooltip position, max width before ellipsis starts, tag color.
Is only shown on deployments and all deployments tables as well as under the status of a single deployment.
As long as the status of a deployment isn't `complete` `failed` `cancelled` and buildStep is present, this hoverable tag is shown
closes #150

add a HoverTag component for deployments/deployment/alldeployments

---

src/components/NewEnvironment/index.js

Updated to capture additional errors (`"Skipped"` & `"Error"`) in the response.

Expanded error handling for New Environment functionality

---

src/components/NewEnvironment/index.js

Truncates deploy keys over 80 characters within the New Environment modal.

Truncate deploy keys over 80 characters - New Environment modal

---

src/components/NewEnvironment/StyledNewEnvironment.tsx
src/components/NewEnvironment/index.js

Instead of hiding Step 2 & 3 when one or more environments are present, they are now wrapped in a collapsable drop-down. This is closed by default but allows users to view the `deploykey` & `webhook` if required.
Workaround for https://github.com/uselagoon/lagoon-ui/issues/191 until the page & components are redesigned.

Exposed deploykey via create environment modal

---

src/components/Deployment/index.js
src/components/Deployments/StyledDeployments.tsx
src/components/Deployments/index.tsx
src/components/HoverTag/index.tsx
src/components/HoverTag/styles.tsx
src/components/LogViewer/LogAccordion/index.js
src/components/LogViewer/StyledLogViewer.tsx
src/components/LogViewer/index.js

Add support for warnings in the UI. This will only ever be exposed when the build provides the necessary information to change the accordions

feat: support warnings

---

src/components/AddVariable/index.js
src/components/EnvironmentVariables/index.js
src/components/ProjectVariables/index.js

Updates the Variables tabs to allow for variables to be created/updated with no value defined.
Includes confirm pop-up when adding/updating variable to have a null value.
Displays empty variables with a `Tag` component:

Change: Allow for empty variable values

---

src/components/BulkDeployments/StyledBulkDeployments.tsx
src/components/BulkDeployments/index.tsx
src/components/Deployments/StyledDeployments.tsx
src/components/Deployments/index.tsx
src/components/DeploymentsByFilter/StyledDeploymentsByFilter.js
src/components/DeploymentsByFilter/index.js

This PR moves the build step status text into a new line
closes #200

move hovertags below status text for deps/bulkdeps/depsbyfilter

---

src/lib/withKeycloak.js

Lagoon currently displays the `username` of the keycloak user in the UI, this field is unchangeable by the user, and Lagoon does not use this field when interacting with users, it uses the `email` field see https://github.com/uselagoon/lagoon/issues/3656
This changes the field to display the email address from the token rather than the preferred_username. This should only be merged if https://github.com/uselagoon/lagoon/issues/3657 is also merged which fixes all the underlying resolver code to use email instead of the username.

fix: use email address in profile, not username

---

src/lib/withKeycloak.js
src/next.config.js

This lets you set an IDP hint for the UI to use so that it can pass directly to a specific IDP instead of the default keycloak login.
This could be used to deploy a UI for a specific IDP

feat: support setting the idp hint as an envvar

---

test/docker-compose.yaml

With the upcoming addition of keycloak migrations to lagoon 2.18, this PR adds that step into the lagoon-minimal setup.

fix: add keycloak migrations container to minimal

---

src/pages/project.js

closes #232 by adding an alpha sort within the deployType
This applies two sorts - an alpha sort on branches, and a id-based sort on PR envs - this will help them maintain their numerical order as below

Order environments by name

---

src/components/Projects/StyledProjects.tsx
src/components/Projects/index.js
src/lib/util.js

Refactor: projects list/filtering

---

src/components/AddTask/components/DrushCron.js
src/components/AddTask/components/Error.tsx
src/components/AddTask/index.js
src/components/AddTask/logic.js
src/lib/ApiConnection.js

Fix: Show actual gql errors for Tasks

---

cypress/support/actions/envOverview/EnvOverviewAction.ts
src/components/DeleteConfirm/index.js
src/components/DeleteConfirm/index.stories.tsx
src/components/Environment/index.js
src/components/NewEnvironment/NewEnvironmentButton/index.js

Redirects to the project page when deleting an environment, rather than remaining on the deleted environment page. Also updates the create environment modal button text to show 'Success' on successful creation to confirm the creation has run successfully. Updates relevant Cypress & Storybook tests.

Change: Redirects on environment deletion + confirmation messaging on environment creation

---

src/components/DeleteVariable/index.js
src/components/EnvironmentVariables/StyledEnvironmentVariables.tsx
src/components/EnvironmentVariables/index.js
src/components/ProjectVariables/StyledProjectVariables.tsx
src/components/ProjectVariables/index.js

Currently when clicking the delete icon for a variable a permission check is run but the delete modal is not opened, subsequent clicks open the modal. This updates the `DeleteVariable` component to hande the permission check and open the modal if permitted. 
This also updates the delete modal button text to show 'Success' on successful deletion to confirm the deletion has run successfully. Also cleans up the loading state for environment and project variable tabs.
closes https://github.com/uselagoon/lagoon-ui/issues/239, closes https://github.com/uselagoon/lagoon-ui/issues/240

Fix: Fixes variable deletion btn & updates the delete modal btn text to confirm successful deletion

---

Dockerfile
cypress/cypress.config.ts
test/docker-compose.yaml
test/keycloak/configure-keycloak.sh

This PR adds an extended network-timeout on yarn install to cover the slow arm64 builders

chore: set network-timeout on yarn install

---

src/components/Organizations/Organizations/OrganizationsSkeleton.tsx
src/components/Organizations/Organizations/index.tsx
src/pages/organizations/index.js

closes #263 
Works identical to how project filtering works on the projects page, except this looks for `name`, `friendlyName` and `description` fields 
Can start setting the search string as page is loading, handles large amounts of organizations asynchronously

Change: add friendlyname and description debounced filtering to organizations page

---

cypress/e2e/organizations/overview.cy.ts
cypress/e2e/rbac/developer.cy.ts
cypress/e2e/rbac/guest.cy.ts
cypress/e2e/rbac/maintainer.cy.ts
cypress/e2e/rbac/reporter.cy.ts
cypress/support/actions/deployment/DeploymentAction.ts
cypress/support/actions/organizations/ProjectsActions.ts
src/components/Organizations/NewProject/StyledNewProject.tsx
src/components/Organizations/NewProject/index.js
src/layouts/GlobalStyles/index.tsx

will close #267 
@shreddedbacon if `branches` and `pullrequests` aren't provided they're set to true, but the api doesn't allow non-string values, so currently this PR sends values as stringified values. seems wrong

change: add branches and pullrequests during org project creation

---

src/components/AddVariable/StyledAddVariable.tsx
src/components/AddVariable/index.js
src/components/AddVariable/logic.js
src/components/ViewVariableValue/StyledViewVariableValue.tsx

Updates the add environment variable form to allow multiline values to accomodate certificates, SSH keys etc.
Also clears data on the add environment variable form when closing the modal.
closes https://github.com/uselagoon/lagoon-ui/issues/257 https://github.com/uselagoon/lagoon-ui/issues/258

Fix: Environment variables - allows multiline values & clears form data on close

---

src/components/Organizations/AddUserToGroup/Styles.tsx
src/components/Organizations/AddUserToGroup/index.js
src/components/Organizations/AddUserToGroupSelect/index.tsx
src/components/Organizations/SharedStyles.tsx

feat: invite user checkbox for add user modals

---

cypress/e2e/organizations/users.cy.ts
src/components/Organizations/GroupMembers/index.js
src/components/Organizations/PaginatedTable/PaginatedTable.tsx
src/components/Organizations/ProjectGroupMembers/ProjectGroupSkeleton.tsx
src/components/Organizations/ProjectGroupMembers/Styles.tsx
src/components/Organizations/ProjectGroupMembers/index.js
src/components/Organizations/ProjectNotifications/ProjectNotificationsSkeleton.tsx
src/components/Organizations/ProjectNotifications/Styles.tsx
src/components/Organizations/ProjectNotifications/index.js
src/components/Organizations/Projects/Styles.tsx
src/components/Organizations/User/index.tsx
src/components/Organizations/Users/index.js

Change: show count on system groups/users and toggle users on by default

---

cypress/support/actions/settings/SettingsAction.ts
cypress/support/repositories/settings/SettingsRepository.ts
src/components/DeleteConfirm/index.js
src/components/DeleteConfirm/index.stories.tsx
src/components/SshKeys/index.js
src/layouts/GlobalStyles/index.tsx
src/lib/query/Me.js

Fixes global styling on the antd modal to allow dark mode to work properly & populates the existing key in the modal. Also adds an error notification instead of rendering a div with the error message, adds a delete confirmation & updates relevant tests.
closes https://github.com/uselagoon/lagoon-ui/issues/289

Fix: Fixes SSHKey modal

---

src/components/BulkDeployments/index.tsx
src/components/DeploymentsByFilter/index.js

uses the formatting function used in `/allDeployments` page

fix: overflowing bulkdeployment texts

---

cypress/e2e/rbac/developer.cy.ts
cypress/e2e/rbac/guest.cy.ts
cypress/e2e/rbac/organizations/orgViewer.cy.ts
cypress/e2e/rbac/reporter.cy.ts
cypress/support/actions/envOverview/EnvOverviewAction.ts
cypress/support/actions/organizations/GroupsAction.ts
cypress/support/actions/organizations/NotificationsAction.ts
cypress/support/actions/organizations/OverviewAction.ts
cypress/support/actions/organizations/ProjectsActions.ts
cypress/support/actions/project/ProjectAction.ts
cypress/support/actions/tasks/TasksAction.ts
test/docker-compose.yaml
tsconfig.json

The recent change in Lagoon https://github.com/uselagoon/lagoon/pull/3736 removed attributes from error messages.
This PR removes the explicit check for these attributes from the Cypress response checks.
It also fixes the KEYCLOAK variable references to match the latest changes in main.

tests: Modify Cypress error attribute checks

---

.github/workflows/ui-workflow.yaml
package.json
yarn.lock

Circumvents temporarily
```
src/components/Projects/index.stories.tsx(21,5): error TS2322: Type 'Project[]' is not assignable to type 'never[]'.
Type 'Project' is not assignable to type 'never'. 
```

chore: pin typescript to 5.6.2

---

.github/workflows/ui-workflow.yaml
cypress/e2e/general/variables.cy.ts
cypress/e2e/organizations/users.cy.ts

A weird nonsense bug that has suddenly appeared as an order of operations glitch - making sure the IdleHandler registers after the page change seems to resolve it :crossed_fingers:

tests: rework some Cypress waits - save screenshots and logs

---

Makefile
cypress/e2e/organizations/groups.cy.ts
cypress/e2e/organizations/notifications.cy.ts
cypress/e2e/organizations/users.cy.ts
cypress/e2e/rbac/maintainer.cy.ts
cypress/e2e/rbac/organizations/orgAdmin.cy.ts
cypress/e2e/rbac/organizations/orgViewer.cy.ts
cypress/e2e/rbac/organizations/platformAndOrgOwnerJourney.cy.ts
cypress/support/actions/organizations/GroupsAction.ts
cypress/support/actions/organizations/NotificationsAction.ts
package.json
src/lib/withKeycloak.js
src/pages/_document.js
yarn.lock

UI library changes to support for Keycloak 26
https://www.keycloak.org/docs/latest/upgrading/#keycloak-js

chore: import keycloak-js

---

cypress/e2e/general/navigation.cy.ts
server.js
src/components/AddVariable/index.js
src/components/DeleteVariable/index.js
src/components/NavTabs/NavTabsSkeleton.tsx
src/components/Organizations/NavTabs/OrgNavTabsSkeleton.tsx
src/components/Organizations/NavTabs/index.js
src/components/Organizations/Variables/StyledVariables.tsx
src/components/Organizations/Variables/VariablesSkeleton.tsx
src/components/Organizations/Variables/index.js
src/components/ProjectNavTabs/ProjectNavTabsSkeleton.tsx
src/components/link/Organizations/Variables.tsx
src/lib/query/organizations/OrganizationByNameWithEnvVars.js
src/lib/query/organizations/OrganizationByNameWithEnvVarsValue.js
src/pages/organizations/variables.js

UI support for https://github.com/uselagoon/lagoon/pull/3856

feat: add org env vars to the organizations section

---

src/lib/subscription/Deployments.js

Add `buildStep` to the deployment subscription so that the build step gets updated.

fix: add buildstep to deployment subscription

---

src/components/Task/index.tsx

Currently task files are duplicated in the `Task` component due to a duplicate map block. This updates the component to remove the errant duplicate block.

Fix: Removes duplicate map block
